64 workshop
matt-hires/nycmm pull request #17
Opened 2021-05-28 07:57 UTC by schnaufman

neue Version der Workshopseite

Die einzelnen Workshops wurden aufgeteilt
Der Plan wurde vorerst durch "Tagesablauf" ersetzt, da die Klassen noch nicht festgelegt sind

Contentupdates ausständig
Überlegung:
Es sind jetzt sehr viele Sections auf dieser Seite

2021-06-18 22:12 UTC, matt-hires reviewed
Super, bzgl. Styling hab ich dann noch was - aber besser mal vorerst die Kleinigkeiten aus die ich angemerkt habe.

2021-06-18 22:12 UTC, matt-hires commented on _includes/sections/workshop/de/scholarship/scholarship.md
> +##### Für Musikstudenten, vergeben wir _„International and National Scholarship Awards“_. Dieses Stipendium ermöglicht die freie Teilnahme am Workshop, sowie freien Eintritt zum Festival. Für eure Be
`{{ "now" | date: "%Y" }}`
Das könnte man generell öfter verwenden um die Jahreszahl/Datum einzusetzen, allerdings nicht mit dem aktuellen Datum sondern mit dem Datum aus der Konfiguration:
siehe: __data/sections/festival.yaml:20_ 
```
format: "{{ site.date.begin | date: \"%d\" }}.{{ site.date.begin | date: \"%m\" }}.{{ site.date.begin | date: \"%Y\" }}"
 ```

2021-06-18 22:12 UTC, matt-hires commented on _includes/sections/workshop/de/tickets/tickets.html
> +  <!--<p class="c-section-workshop-tickets-info">*&nbsp;Ermäßigung für Schüler/Studenten/Jugendliche bis zum vollendeten 21. Lebensjahr.</p>-->
Kommentar entfernen.

2021-06-18 22:12 UTC, matt-hires commented on _includes/sections/workshop/de/tickets/tickets.html
> +          <!--<a class="button c-section-workshop-tickets-ticket-order-btn" target="_blank" rel="noopener noreferrer" href="{{ticket.link}}">Anmelden</a>-->
Kommentar entfernen.

2021-06-18 22:12 UTC, matt-hires commented on _includes/sections/workshop/de/tickets/tickets.html
> +            <h2 class="c-section-workshop-tickets-ticket-price">{{ticket.price.regular}}<!--<span>&nbsp;/&nbsp;{{ticket.price.discount}}&nbsp;*</span>--></h2>
Kommentar entfernen.

2021-06-23 10:53 UTC, schnaufman commented
Hab die Kommentare entfernt
Gute Idee mit dem Datum, hoffe das passt so, ist ein bisschen anders formatiert.
```
deadline: 
    format: "{{ section.deadline.date | date: \"%d.%m.%Y\" }}"
    date: "2021-06-30"
```
einziges Problem: nimmt  man beim monat %B eingibt, steht das Monat in Englisch da, ich hab leider nicht herausgefunden, wie man das ändert.
Ist aber nicht schlimm, jetzt steht halt 30.6.2021 dort :D

2021-07-09 15:34 UTC, matt-hires commented
> Hab die Kommentare entfernt
> Gute Idee mit dem Datum, hoffe das passt so, ist ein bisschen anders formatiert.
> 
> ```
> deadline: 
>     format: "{{ section.deadline.date | date: \"%d.%m.%Y\" }}"
>     date: "2021-06-30"
> ```
> 
> einziges Problem: nimmt man beim monat %B eingibt, steht das Monat in Englisch da, ich hab leider nicht herausgefunden, wie man das ändert.
> Ist aber nicht schlimm, jetzt steht halt 30.6.2021 dort :D

leider geht das nicht automatisch, die Übersetzung müsstest du manuell machen, Bsp.:
```
{% assign m = page.date | date: "%-m" %}
{{ page.date | date: "%-d" }}
{% case m %}
  {% when '1' %}Januar
  {% when '2' %}Februar
  {% when '3' %}März
  {% when '4' %}April
  {% when '5' %}Mai
  {% when '6' %}Juni
  {% when '7' %}Juli
  {% when '8' %}August
  {% when '9' %}September
  {% when '10' %}Oktober
  {% when '11' %}November
  {% when '12' %}Dezember
{% endcase %}
{{ page.date | date: "%Y" }}
```

2021-07-09 15:45 UTC, matt-hires requested changes
Bitte die Kleinigkeiten noch ausbessern :1st_place_medal:

2021-07-09 15:45 UTC, matt-hires commented on _includes/sections/workshop/de/classes/classes.html
> +    {% when 0 %}
Raffinierte Idee :+1: 

Allerdings wenn du jedem zweiten Block eine andere Farbe/Style geben willst sieh dir das an:

https://github.com/matt-hires/nycmm/blob/bd861375274c0bb7ad761f04c6f2d2cc9330d8ab/assets/scss/layouts/_l-sections.scss#L6-L7

2021-07-09 15:45 UTC, matt-hires commented on _includes/sections/workshopdetails/de/workshopdetails/workshopdetails.html
> +</div>
New Line ans Ende des Files einfügen.
Ist best-practice :)

2021-07-09 15:45 UTC, matt-hires commented on assets/scss/layouts/sections/_l-workshop.scss
> +}
New-Line ans Ende des Files einfügen.

2021-07-09 15:59 UTC, matt-hires commented
Außerdem ist mir noch aufgefallen dass es die Workshopdetails nur in Deutsch gibt, ist das Absicht?
https://deploy-preview-17--nycmm.netlify.app/workshopdetails/

2021-07-11 20:42 UTC, schnaufman commented
Danke für die Ideen.
Ich hab versucht, das Styling ein bisschen zu verbessern :D

Das Datum beim Stipendium lass ich erstmal als Zahl stehen, das stört niemanden.
Die Workshopdetails-Seite muss auch noch nicht in Englisch verfügbar sein, es gibt eh noch keine Texte :)

2021-07-14 17:21 UTC, matt-hires approved these changes
Nice work :+1:

2021-07-14 17:21 UTC, merged