* First Changes About Us
matt-hires/nycmm pull request #8
Opened 2021-03-03 19:24 UTC by schnaufman

meine ersten Änderungen auf der Über Uns Seite

2021-03-28 13:41 UTC, matt-hires requested changes
@schnaufman 

- [x]  Bitte die Bilder noch verkleinern bzw. weiter komprimieren.

Größenveränderungen wie im Screenshot anbei verlangsamen die Ladezeiten:
![Screenshot from 2021-03-28 15-40-06](https://user-images.githubusercontent.com/23478257/112754343-ea831100-8fdb-11eb-959d-c13d68325883.png)

Eine Möglichkeit diese Bilder zu verkleinern findest du hier:
https://docs.gimp.org/en/gimp-tutorial-quickie-jpeg.html

- [ ] Außerdem noch bitte lquips generieren.

2021-03-28 13:41 UTC, matt-hires commented on _data/sections/about.yml
> +  folder: "Famtag"
@schnaufman 
"Famtag" **muss** klein geschrieben werden, da der Ordner auch klein geschrieben wurden.
❗Ordner sind nur auf Windows case-insensitive.

2021-03-30 13:11 UTC, schnaufman commented
Bilder wurden komprimiert, bzw nicht gebrauchte entfernt.
Beim lqip generieren krieg ich immer noch einen Error, siehe [lqip error.txt](https://github.com/matt-hires/nycmm/files/6229224/lqip.error.txt)
Nimmt man in der Kommandozeile statt "gm" "magick" funktioniert der Befehl.

2021-03-30 19:57 UTC, matt-hires commented
Du brauchst noch "Graphicsmagick"(https://sourceforge.net/projects/graphicsmagick/), danach solltest du die lquips wie folgt in der gitbash generieren können:
```
$ node ./helpers/create_lqip.js
```

2021-03-30 20:01 UTC, matt-hires commented
In diesem Mergerequest sieht man jetzt auch schon dass das Deployment funktioniert und du kannst deine Änderungen live ansehen:
![Screenshot from 2021-03-30 21-58-59](https://user-images.githubusercontent.com/23478257/113049074-8448ea80-91a3-11eb-86ef-4e89b92174ab.png)

2021-03-30 21:18 UTC, schnaufman commented
Danke! Leider hab ich jetzt einen anderen Fehler... [lqip error.txt](https://github.com/matt-hires/nycmm/files/6232222/lqip.error.txt)

2021-04-02 08:50 UTC, matt-hires commented
Hast du das ganze mit gitbash ausgeführt?
Falls ja, schreib mir bitte deine `PATH` Variable, siehe
```
echo $PATH
/c/Users/IEUser/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/IEUser/bin:/c/program files/graphicsmagick-1.3.36-q16:/c/Program Files/ImageMagick-7.0.10-Q16-HDRI:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/ProgramData/chocolatey/bin:/c/Program Files/Puppet Labs/Puppet/bin:/c/Program Files (x86)/Common Files/Propellerhead Software/ReWire:/c/Program Files/Common Files/Propellerhead Software/ReWire:/c/Program Files/nodejs:/cmd:/c/Ruby27-x64/bin:/c/Users/IEUser/AppData/Local/Microsoft/WindowsApps:/c/Users/IEUser/AppData/Roaming/npm:/usr/bin/vendor_perl:/usr/bin/core_perl
```
In meiner VM hat das tadellos funktioniert, auch mit deinem Branch.
[lquip.log](https://github.com/matt-hires/nycmm/files/6248644/lquip.log)

2021-04-03 17:42 UTC, schnaufman commented
Ja, wurde mit GitBash gemacht, meine Path Variable
```known@DESKTOP-49FRUV2 MINGW64 ~/Documents/NYCMM/nycmm (martin)
$ echo $PATH
/mingw64/bin:/usr/bin:/c/Users/known/bin:/c/Python39/Scripts:/c/Python39:/c/program files/graphicsmagick-1.3.36-q16:/c/Program Files/ImageMagick-7.0.11-Q16-HDRI:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/cmd:/c/Program Files/nodejs:/c/ProgramData/chocolatey/bin:/c/Ruby27-x64/bin:/c/Users/known/AppData/Local/Microsoft/WindowsApps:/c/Users/known/AppData/Local/Programs/Microsoft VS Code/bin:/c/Users/known/AppData/Roaming/npm```

ich hab mir gestern node noch einmal neu installiert, da ich beim letzten Mal chocolatey nicht dabei hatte, jetzt geht grad noch weniger wie vorher
...
Ich werd mir jetzt mal eine Linux Partition einrichten und versuch da mein Glück.

2021-04-03 17:50 UTC, matt-hires commented
Ich glaub ich weiß schon was das Problem ist/war:
```
Unsupported MIME type: image/webp
C:\Users\known\Documents\NYCMM\nycmm\node_modules\lqip\index.js:76
  throw up;
  ^
```
Du hast vermutlich schon weitere Bilder in deinem Branch hinzugefügt. Unter anderem welche, mit einem nicht unterstützten Mimetype ("image/webp"). Bitte nur `png`s verwenden wenn möglich, ansonsten müssen wir das lqip Script erweitern.

Du könntest zum Test mal deinen aktuellen Changes *stashen* und dann das Script noch einmal ausführen.

2021-04-03 21:38 UTC, schnaufman commented
Hab das webp Bild gefunden & ersetzt und dann alle Bilder als pngs verwendet.
Unter Linux hats dann auch gar keine Probleme gegeben :D
Lqips wurden generiert

2021-04-04 10:00 UTC, merged